export var jb = {
	component: jb_component,
	resource: jb_resource,
	type: jb_type,
	Ctx: jbCtx,
	ctx: jb_ctx,
//	expression: jb_expression,
	comps: jbart.comps,
	compName: jb_compName,
	isProfOfType: jb_isProfOfType,

	logException: jb_logException,
	logError: jb_logError,
	logPerformance: jb_logPerformance,

	widgets: jbart_widgets,
//	run: jb_run,
	bind: jb_bind,
	trigger: jb_trigger,

	equals: jb_equals,
	val: jb_val,
	writeValue: jb_writeValue,
	prettyPrint: jb_prettyPrint,
	stringify: jb_prettyPrint,
	path: jb_path,
	toarray: jb_toarray,
	tostring: jb_tostring,
	delay: jb_delay,

	extend: jb_extend,
	map: jb_map,
	obj: jb_obj,
	ownPropertyNames: jb_ownPropertyNames,
	firstProp: jb_firstProp,
	range: jb_range,
	entries: jb_entries,
	flattenArray: jb_flattenArray,
	compareArrays: jb_compareArrays,
	writeToResource: jb_writeToResource,
}
